---
title: "5293 Proposal for Final Project"
author:
  - Hao Chang
  - Jiachen Liu
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '2'
---
# Basic information

Team Number: Group 37

Team Members: Jiachen Liu (jl5991), Hao Chang (hc3207)

# Questions:
  1.The structure of the damage brought from the disaster in the different time periods.
  
  2.The relationship between disaster damage and economic (technological) development in different time periods/countries.
  
  3.The special aspects of COVID compared to other types of disasters.

# Dataset:
  1.The International Disaster Data Center for research on the Epidemiology of Disaster
    
  LINK:https://public.emdat.be/data
    
  DESCRIPTION: EM-DAT contains essential core data on the occurrence and effects of over 22,000 mass disasters in the             world from 1900 to the present day. The database is compiled from various sources, including UN                             agencies,non-governmental organizations, insurance companies, research institutes, and press agencies.
  
  2.Economic Data (GDP) - World Bank Database
    
  LINK:https://datacatalog.worldbank.org/search/dataset/0037712/World-Development-Indicators
  
  3.JHU CSSE COVID-19 Dataset
    
  LINK:https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
    
  DESCRIPTION: This is the data repository for the 2019 Novel Coronavirus Visual Dashboard operated by the Johns Hopkins          University Center for Systems Science and Engineering (JHU CSSE). Also, Supported by the ESRI Living Atlas Team and         the Johns Hopkins University Applied Physics Lab (JHU APL).

# How data will help:
  To answer the first question, we will group our data by disaster types and year, and compare the death number and economic     losses.
  
  To answer the second question, we will join our first two datasets by countries and years, and see if there are some          interesting correlations.
  
  To answer the third question, we will compare the first and third datasets, compare the death number distribution, and        find some patterns.
